name: "Gather statistics"
description: "Gathers repository statistics"
inputs:
  owner:
    description: "Repository owner name"
    required: true
    default: "AndreiLobanovich"
  repository:
    description: "Repository name"
    required: true
    default: "actions_test_task"
  dateSince:
    description: "Date since which statistics should be gathered"
    required: false
outputs:
  totalPrs:
    description: "Total number of PRs"
  openPrs:
    description: "Number of opened PRs"
  closedPrs:
    description: "Number of closed PRs"
  totalIssues:
    description: "Total number of issues"
  openIssues:
    description: "Number of open issues"
  closedIssues:
    description: "Number of closed issues"
runs:
  using: "node16"
  main: "index.js"
