name: "Gather statistics"
description: "Gathers repository statistics"
inputs:
  owner:
    description: "Repository owner name"
    required: true
    default: "AndreiLobanovich"
  repository:
    description: "Repository name"
    required: true
    default: "actions_test_task"
  monthsAgo:
    description: "How long ago in months since now shoul statistics be gathered"
    required: false
    default: "1"
runs:
  using: "node16"
  main: ".github/actions/index.js"
